### ISSUE TITLE
有Promise了为什么还要用Thunk？

### ISSUE THREAD

**Issue by hax** [thunks/thunks#1]
建议给个比较。

**Comment by think2011** [comment]
从redux的文档实例追到这里，原来thunk并不是什么新鲜东西。

看了一下时间，现在是2015年12月了..

**Comment by zensh** [comment]
用到现在，只发现了两个核心的区别，这是 promise 无法实现的，当然选择可以避开：
1. thunk 可以传递 `this`;
2. thunk 可以惰性求值

**Comment by fengmk2** [comment]
@zensh 已经被好几个忘记 catch 的问题烦心，特别是写 cli 工具类的。。。

**Comment by zensh** [comment]
@fengmk2 什么样的情形？给个 demo？
