### ISSUE TITLE
为什么不加入一些流程控制相关的方法，不用借助其他库就可以畅快的完成一些简单的流程任务

### ISSUE THREAD

**Issue by gavinning** [thunks/thunks#13]
我看到thunk的all方法和seq方法，参数数组里的元素都是thunk对象，为什么不可以是普通数组呢。

比如这样：

thunk
    .each(arr, fn)
    .seq(fn)

each处理数组返回符合seq的要求的数组，这样来处理，在一个流程中处理完一个需求

场景：处理20条异步任务，任务全部完成后返回处理结果

thunk
    .each(getList(20), fn)
    .seq(fn)

**Comment by orangemi** [comment]
function getList(l)是返回数组对象？
试试这样：
```
// do parallel
thunk.all(getList(20).map(function(one) {
  return function (callback) {
    // do something each one
  }
}))(function(err, result) {
  // all result will be in result
})

// do in sequence
thunk.seq(getList(20).map(function(one) {
  return function (callback) {
    // do something each one
  }
}))(function(err, result) {
  // all result will be in result
})
```

**Comment by orangemi** [comment]
`thunk.all`和`thunk.seq`都可以以数组作为参数的。
[`thunk.seq([thunk1, ..., thunkX])`](https://github.com/thunks/thunks#thunkseqthunk1--thunkx)
[`thunk.seq(thunk1, ..., thunkX)`](https://github.com/thunks/thunks#thunkseqthunk1--thunkx-1)

[`thunk.all(obj)`](https://github.com/thunks/thunks#thunkallobj)
[`thunk.all(thunk1, ..., thunkX)`](https://github.com/thunks/thunks#thunkallthunk1--thunkx)

其中`thunk.all`参数obj可以是任何thunk集合，包括数组形式。

**Comment by zensh** [comment]
楼上正解，目前的 API 已经足够 hold 住所有控制流程

**Comment by gavinning** [comment]
ok 受教了，我试试~
